### ISSUE TITLE
왜 사이트 미리보기 사진이 노란 리본으로 나오는거지?

### ISSUE THREAD

**Issue by stories2** [UTA-CONNECT/Landing-page#17]

**Comment by stories2** [comment]
<img width="254" alt="스크린샷 2021-06-03 오후 7 03 46" src="https://user-images.githubusercontent.com/16532326/120627239-6e56ef00-c49e-11eb-97ec-39f2dbf6a1db.png">

**Comment by CT-1326** [comment]
제일 먼저 로딩 되는 리소스 순위 별로 프리뷰 뜨는걸로 암

굳이 문제 될게 잇나?

**Comment by stories2** [comment]
프리뷰가 이상하게 뜨는 사이트는 별로 누르고 싶지 않는 느낌도 들고 어짜피 이야기 나올꺼 같음

**Comment by stories2** [comment]
![스크린샷 2021-06-03 오후 11 15 01](https://user-images.githubusercontent.com/16532326/120659667-8855f900-c4c1-11eb-82a6-280ca7a096df.png)

[레퍼런스](https://medium.com/@jjungmin/%EC%9B%B9%EB%A7%81%ED%81%AC-%EB%AF%B8%EB%A6%AC%EB%B3%B4%EA%B8%B0-%ED%99%94%EB%A9%B4-%EB%B3%B4%EC%97%AC%EC%A3%BC%EA%B8%B0-ogtag-26e0025c9520)
