### ISSUE TITLE
더 알아보기 버튼

### ISSUE THREAD

**Issue by CT-1326** [UTA-CONNECT/Landing-page#29]
_폰트 적용_

**Comment by stories2** [comment]
348ed82
에서 상단에 큰 코네 일러 제외 나머지 태그들을 묶어버리는 작업이 있어 풀리퀘 할때 충돌발생할 수 있어

**Comment by CT-1326** [comment]
> 348ed82
> 에서 상단에 큰 코네 일러 제외 나머지 태그들을 묶어버리는 작업이 있어 풀리퀘 할때 충돌발생할 수 있어

잘 부탁합니다 센빠이^^7
